'use strict';
const $ = id => document.getElementById(id);
const state = {session:null, agents:[], run:null, approval:null, approvalEpoch:0, approvalTarget:null, nextCursor:null, pending:null};
const statuses = {QUEUED:'排队中',RUNNING:'处理中',WAITING_INPUT:'等待人工确认',WAITING_APPROVAL:'等待审批',PAUSED:'已暂停',COMPLETED:'已完成',CANCELLED:'已取消',FAILED:'处理失败',EXPIRED:'已到期',BUDGET_EXCEEDED:'达到用量上限',NEEDS_ATTENTION:'需要人工处理'};
const eventNames = {RUN_CREATED:'咨询已创建',RUN_STARTED:'开始处理',RUN_COMPLETED:'处理完成',RUN_FAILED:'处理失败',APPROVAL_REQUESTED:'请求人工确认',APPROVAL_DECIDED:'人工确认已提交',RUN_PAUSED:'任务已暂停',RUN_RESUMED:'任务继续处理',RUN_CANCELLED:'任务已取消',CONTROL_REQUESTED:'控制请求已提交',TOOL_COMPLETED:'资料查询完成',MODEL_COMPLETED:'答复已生成',RUN_STATE_CHANGED:'处理进度已更新'};
function notice(message, retry=false){$('noticeText').textContent=message;$('notice').hidden=false;$('retryCommand').hidden=!retry;}
function errorMessage(error){const codes={SESSION_REQUIRED:'会话已失效，请重新输入访问码。',ACCESS_CODE_INVALID:'访问码不正确。',LOGIN_RATE_LIMITED:'尝试次数较多，请一分钟后再试。',FORBIDDEN:'当前身份没有此操作权限。',NOT_FOUND:'没有找到当前身份可查看的记录。',RELEASE_UNAVAILABLE:'该助手当前不可用，请刷新后选择。',PRECONDITION_FAILED:'记录已更新，请先刷新再操作。',ETAG_MISMATCH:'记录已更新，请先刷新再操作。',APPROVAL_STALE:'审批已变化，请重新查看待确认内容。',INPUT_INVALID:'咨询内容不符合该助手的要求。',QUOTA_EXCEEDED:'当前任务较多，请等待已有任务结束。',TEMPORARILY_UNAVAILABLE:'平台暂时不可用，请稍后查看记录。'};return codes[error.code]||(error.status===412?'记录已更新，请先刷新再操作。':error.message||'操作未完成，请刷新查看最新状态。');}
async function api(path, method='GET', body){let response;try{response=await fetch(path,{method,credentials:'same-origin',redirect:'error',headers:method==='POST'?{'Content-Type':'application/json','X-CSRF-Token':state.session?.csrfToken||''}:{},body:body===undefined?undefined:JSON.stringify(body)});}catch{throw{message:'连接中断，结果可能尚未显示。请先查看运行记录，或使用同一请求重试。',outcomeUnknown:method==='POST'};}let data;try{data=await response.json();}catch{throw{message:'服务响应不完整，请查看最新记录。',outcomeUnknown:method==='POST'};}if(!response.ok){if(response.status===401||data.code==='SESSION_REQUIRED')expireSession();throw{...data,status:response.status};}return data;}
function busy(value){$('createButton').disabled=value||!selectedAgent();document.querySelectorAll('[data-control]').forEach(button=>button.disabled=value);$('approveButton').disabled=value||!state.approval?.reviewComplete||state.approval?.status!=='PENDING';$('rejectButton').disabled=value||state.approval?.status!=='PENDING';const pendingReview=value&&Boolean(state.pending?.reviewRunId);$('reviewRunId').disabled=pendingReview;$('reviewForm').querySelector('button').disabled=pendingReview;}
async function command(path,body,reviewRunId=null){if(state.pending){notice('上一次请求的结果尚不明确，请先使用同一请求重试。',true);return null;}state.pending={path,body,reviewRunId};return sendPending();}
async function sendPending(){const pending=state.pending;if(!pending)return null;busy(true);try{const result=await api(pending.path,'POST',pending.body);state.pending=null;if(pending.reviewRunId)invalidateApproval();notice('请求已提交。');return result;}catch(error){const uncertain=Boolean(state.session)&&(error.outcomeUnknown||error.status>=500);if(!uncertain)state.pending=null;notice(errorMessage(error)+(uncertain&&pending.reviewRunId?' 原审批运行编号：'+pending.reviewRunId:''),uncertain);return null;}finally{busy(Boolean(state.pending));}}
function invalidateApproval(){state.approvalEpoch++;state.approval=null;state.approvalTarget=null;$('approvalPanel').hidden=true;$('reviewInput').value='';$('reviewReason').value='';$('reviewInput').disabled=true;$('reviewReason').disabled=true;$('approvalSummary').textContent='';$('approvalFields').replaceChildren();for(const id of ['approvalRunId','approvalRevision','approvalDigest','approvalId'])$(id).textContent='';$('approveButton').disabled=true;$('rejectButton').disabled=true;}
function expireSession(){state.pending=null;state.run=null;state.agents=[];invalidateApproval();$('runPanel').hidden=true;$('runList').replaceChildren();$('reviewRunId').value='';busy(false);setSession({signedIn:false});notice('会话已失效，请重新登录。之前的写请求不会自动重新提交。');}
function setSession(session){state.session=session.signedIn?session:null;$('loginPanel').hidden=Boolean(state.session);$('workspace').hidden=!state.session;$('logout').hidden=!state.session;$('roleLabel').textContent=state.session?(session.role==='reviewer'?'审核员':'客服专员'):'';$('operatorPanel').hidden=session.role!=='operator';$('reviewerPanel').hidden=session.role!=='reviewer';$('projectLabel').textContent=session.project||'';$('workspaceTitle').textContent=session.role==='reviewer'?'人工确认工作台':'客服工作台';$('workspaceSubtitle').textContent=session.role==='reviewer'?'核对待确认内容，留下明确的人工决定。':'从合成咨询开始，查看每次任务的答复与进度。';if(session.role==='operator')Promise.all([loadAgents(),loadRuns()]).catch(error=>notice(errorMessage(error)));}
async function loadAgents(){const result=await api('/api/agents');state.agents=result.body.items||[];$('agentSelect').replaceChildren();for(const agent of state.agents){const option=document.createElement('option');option.value=agent.releaseRef.releaseId;option.textContent=(agent.name||agent.agentId)+' · 版本 '+agent.version+(agent.isDefault?' · 默认':'');$('agentSelect').append(option);}const preferred=state.agents.find(agent=>agent.isDefault);if(preferred)$('agentSelect').value=preferred.releaseRef.releaseId;renderInputs();}
function selectedAgent(){return state.agents.find(agent=>agent.releaseRef.releaseId===$('agentSelect').value);}
function renderInputs(){const agent=selectedAgent();$('inputFields').replaceChildren();$('createButton').disabled=!agent||Boolean(state.pending);$('agentDescription').textContent=agent?'使用已发布版本处理本次咨询。':'当前还没有可调用的助手，请联系管理员完成发布。';if(!agent)return;const properties=agent.inputSchema?.properties||{},required=agent.inputSchema?.required||[];for(const [name,schema] of Object.entries(properties)){const label=document.createElement('label');label.textContent=schema.title||({question:'客户问题',orderId:'示例订单号',message:'咨询内容'}[name]||name);const input=document.createElement(schema.type==='string'&&name!=='orderId'?'textarea':'input');input.dataset.field=name;input.dataset.kind=schema.type;input.id='field-'+name;label.htmlFor=input.id;if(input.tagName==='TEXTAREA')input.rows=4;if(schema.type==='number'||schema.type==='integer'){input.type='number';if(schema.type==='integer')input.step='1';}else if(schema.type==='boolean'){input.type='checkbox';}else if(schema.type!=='string'){$('agentDescription').textContent='此助手的输入形式暂不适合客服工作台，请选择其他助手。';$('createButton').disabled=true;return;}input.required=required.includes(name)&&schema.type!=='boolean';if(schema.maxLength)input.maxLength=Math.min(schema.maxLength,12000);if(schema.default!==undefined){if(schema.type==='boolean')input.checked=Boolean(schema.default);else input.value=String(schema.default);}$('inputFields').append(label,input);if(schema.description){const hint=document.createElement('p');hint.className='hint';hint.textContent=schema.description;$('inputFields').append(hint);}}}
function inputs(){const result=Object.create(null);for(const field of $('inputFields').querySelectorAll('[data-field]')){if(field.dataset.kind==='boolean')result[field.dataset.field]=field.checked;else if(field.value!==''||field.required)result[field.dataset.field]=['number','integer'].includes(field.dataset.kind)?Number(field.value):field.value;}return result;}
async function loadRuns(cursor=null){const result=await api('/api/runs'+(cursor?'?cursor='+encodeURIComponent(cursor):''));if(!cursor)$('runList').replaceChildren();const items=result.body.items||[];if(!items.length&&!cursor){const empty=document.createElement('p');empty.className='empty';empty.textContent='尚无咨询记录，提交一个合成问题开始。';$('runList').append(empty);}for(const run of items){const button=document.createElement('button');button.className='run-row';const left=document.createElement('span');left.textContent=run.releaseRef?.agentId||'客服咨询';const small=document.createElement('small');small.textContent=new Date(run.createdAt).toLocaleString('zh-CN')+' · '+run.id.slice(0,8);left.append(small);const status=document.createElement('span');status.className='status';status.textContent=statuses[run.status]||run.status;button.append(left,status);button.addEventListener('click',()=>showRun(run.id).catch(error=>notice(errorMessage(error))));$('runList').append(button);}state.nextCursor=result.body.nextCursor;$('moreRuns').hidden=!state.nextCursor;}
async function showRun(id){const result=await api('/api/runs/'+encodeURIComponent(id));state.run={...result.body,etag:result.etag};$('runPanel').hidden=false;$('runId').textContent=id;$('runStatus').textContent=statuses[result.body.status]||result.body.status;const usage=result.body.usage;$('runUsage').textContent=usage?'模型调用 '+usage.modelCalls+' 次 · 用量 '+usage.chargedTokens+' tokens':'';const output=result.body.output;$('runOutput').textContent=output?.visibility==='AVAILABLE'?humanOutput(output.value):(result.body.status==='WAITING_INPUT'?'请将运行编号交给审核员，完成待确认答复。':'尚无可显示的答复。请刷新查看处理进度。');const events=await api('/api/runs/'+encodeURIComponent(id)+'/events');$('events').replaceChildren();for(const event of events.body.items||[]){const item=document.createElement('li');item.textContent=(eventNames[event.type]||'处理记录')+' · '+new Date(event.at).toLocaleString('zh-CN');$('events').append(item);}}
function humanOutput(value){if(typeof value==='string')return value;if(value==null)return '任务已完成。';for(const key of ['answer','text','input','content','response'])if(typeof value[key]==='string')return value[key];if(value.result)return humanOutput(value.result);return JSON.stringify(value,null,2);}
async function showApproval(id){invalidateApproval();const target=id.trim(),epoch=state.approvalEpoch;state.approvalTarget=target;let result;try{result=await api('/api/runs/'+encodeURIComponent(target)+'/approval');}catch(error){if(epoch!==state.approvalEpoch)return;throw error;}if(epoch!==state.approvalEpoch||$('reviewRunId').value.trim()!==target)return;if(result.body?.runId!==target||!result.etag||!result.body.id||!result.body.digest||!result.body.runRevision){invalidateApproval();throw{message:'审批响应与当前运行不一致，请重新查询。'};}state.approval={...result.body,etag:result.etag,loadedEpoch:epoch};$('reviewInput').value='';$('reviewReason').value='';$('reviewInput').disabled=false;$('reviewReason').disabled=false;$('approvalPanel').hidden=false;$('approvalTitle').textContent=result.body.kind==='HUMAN_INPUT'?'确认客服答复':'确认待执行操作';$('approvalRunId').textContent=result.body.runId;$('approvalRevision').textContent=result.body.runRevision;$('approvalDigest').textContent=result.body.digest;$('approvalId').textContent=result.body.id;$('approvalSummary').textContent=result.body.summary;$('approvalFields').replaceChildren();for(const field of result.body.fields||[]){const line=document.createElement('p');line.textContent=field.name+'：'+(field.masked?'内容已隐藏':field.value);$('approvalFields').append(line);}$('reviewInput').hidden=!result.body.inputRequired;$('reviewInputLabel').hidden=!result.body.inputRequired;$('approvalExpiry').textContent='有效期至 '+new Date(result.body.expiresAt).toLocaleString('zh-CN')+' · '+(result.body.status==='PENDING'?'等待决定':'当前审批已结束');busy(Boolean(state.pending));}
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();try{const session=await api('/api/session','POST',{accessCode:$('accessCode').value});$('accessCode').value='';setSession(session);}catch(error){notice(errorMessage(error));}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout','POST',{});location.reload();}catch(error){notice(errorMessage(error));}});
$('agentSelect').addEventListener('change',renderInputs);
document.querySelectorAll('[data-example]').forEach(button=>button.addEventListener('click',()=>{const field=$('inputFields').querySelector('[data-field="question"]')||$('inputFields').querySelector('textarea');if(field)field.value=button.dataset.example;}));
$('createForm').addEventListener('submit',async event=>{event.preventDefault();const agent=selectedAgent();if(!agent)return;const result=await command('/api/runs',{agentId:agent.agentId,releaseId:agent.releaseRef.releaseId,inputs:inputs(),requestKey:crypto.randomUUID()});if(result)try{await showRun(result.body.run.id);await loadRuns();}catch(error){notice(errorMessage(error));}});
$('refreshRuns').addEventListener('click',()=>loadRuns().catch(error=>notice(errorMessage(error))));$('moreRuns').addEventListener('click',()=>loadRuns(state.nextCursor).catch(error=>notice(errorMessage(error))));$('refreshRun').addEventListener('click',()=>state.run&&showRun(state.run.id).catch(error=>notice(errorMessage(error))));
document.querySelectorAll('[data-control]').forEach(button=>button.addEventListener('click',async()=>{if(!state.run)return;const result=await command('/api/runs/'+state.run.id+'/'+button.dataset.control,{etag:state.run.etag,requestKey:crypto.randomUUID()});if(result)showRun(state.run.id).catch(error=>notice(errorMessage(error)));}));
$('reviewRunId').addEventListener('input',invalidateApproval);
$('reviewForm').addEventListener('submit',event=>{event.preventDefault();showApproval($('reviewRunId').value.trim()).catch(error=>notice(errorMessage(error)));});
async function decide(decision){const approval=state.approval;if(!approval||approval.runId!==$('reviewRunId').value.trim()||approval.runId!==state.approvalTarget||approval.loadedEpoch!==state.approvalEpoch){invalidateApproval();notice('请先重新查询并核对当前运行的审批内容。');return;}if(approval.status!=='PENDING'||(decision==='APPROVE'&&!approval.reviewComplete)){notice('当前审批不可提交，请重新查询。');return;}if(!$('reviewReason').value.trim()){notice('请填写本次审核说明。');return;}const body={approvalId:approval.id,digest:approval.digest,decision,reason:$('reviewReason').value,etag:approval.etag,requestKey:crypto.randomUUID()};if(decision==='APPROVE'&&approval.inputRequired){if(!$('reviewInput').value.trim()){notice('请填写核对后的客服答复。');return;}body.input=$('reviewInput').value;}const result=await command('/api/runs/'+approval.runId+'/decision',body,approval.runId);if(result){invalidateApproval();notice(decision==='APPROVE'?'人工确认已提交，任务可继续处理。':'拒绝决定已提交。');}}
$('approveButton').addEventListener('click',()=>decide('APPROVE'));$('rejectButton').addEventListener('click',()=>decide('REJECT'));
$('retryCommand').addEventListener('click',async()=>{const result=await sendPending();if(result?.body?.run&&state.session.role==='operator')showRun(result.body.run.id).catch(error=>notice(errorMessage(error)));});$('dismissNotice').addEventListener('click',()=>{$('notice').hidden=true;});
api('/api/session').then(setSession).catch(error=>notice(errorMessage(error)));
